# Solo para pruebas locales o en runner de github...

services:

  portfolio:
    build: ./portfolio
    container_name: portfolio-container
    env_file:
      - ./portfolio/.env
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - network-portfolio

  db:
    build: ./db
    container_name: db-container
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./db/.env
    networks:
      - network-portfolio

volumes:
  db-data:
    driver: local

networks:
  network-portfolio:
    driver: bridge

