# Solo para pruebas locales o en runner de github...

services:

  portfolio:
    build: ./portfolio
    container_name: portfolio-container
    environment:
    - MYSQL_DATABASE_DB=${MYSQL_DATABASE}
    - MYSQL_DATABASE_USER=${MYSQL_USER}
    - MYSQL_DATABASE_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE_HOST=${MYSQL_DATABASE_HOST}
    - MYSQL_DATABASE_PORT=${MYSQL_DATABASE_PORT}
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - network-portfolio

  db:
    build: ./db
    container_name: db-container
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - network-portfolio

volumes:
  db-data:
    driver: local

networks:
  network-portfolio:
    driver: bridge

