name: Portfolio Deploy
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      MYSQL_DATABASE_DB: ${{ secrets.MYSQL_DATABASE_DB }}
      MYSQL_DATABASE_HOST: ${{ secrets.MYSQL_DATABASE_HOST }}
      MYSQL_DATABASE_PASSWORD: ${{ secrets.MYSQL_DATABASE_PASSWORD }}
      MYSQL_DATABASE_USER: ${{ secrets.MYSQL_DATABASE_USER }}
      MYSQL_DATABASE_PORT: ${{ secrets.MYSQL_DATABASE_PORT }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
         
      - name: Ejecutar entrypoint.sh
        run: |
          chmod +x entrypoint.sh
          ./entrypoint.sh