name: Portfolio Deploy
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      # Otras variables necesarias...
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin

      - name: Build and push Portfolio image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/portfolio:latest -f portfolio/Dockerfile portfolio
          docker push $DOCKER_HUB_USERNAME/portfolio:latest

      - name: Build and push DB image (opcional)
        run: |
          docker build -t $DOCKER_HUB_USERNAME/db:latest -f db/Dockerfile db
          docker push $DOCKER_HUB_USERNAME/db:latest